### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by StApostol** [remotelyliving/php-query-bus#1]
In your result class, constructor arguments do not match return objects in getters

```php
public function __construct(?\stdClass $user, GetUserProfileResult $userProfileResult = null)
public function getUser(): ?\stdClass
public function getUserProfileResult(): ?GetUserProfileResult
```

**Comment by remotelyliving** [comment]
Thanks for pointing this out, I could see how it's a little confusing. The constructor arg is optional and will will either be set to `GetUserProfileResult` or `null`, butI can update it to have `?` as it should allow a null value either way. I've updated it, and thank you again!
